import {useCallback,useEffect,useRef,useState} from 'react'
import JSZip from 'jszip'
import {Download,ImagePlus,RotateCcw,Sparkles,Upload,Eye,Info} from 'lucide-react'
import type {AppSettings,PreviewMode,ProcessedImage,DotShape} from './types'
import {imageDataToBlob,imageDataToCanvas,processImage} from './lib/halftone'

const defaults:AppSettings={dpi:300,halftone:{lpi:30,angle:45,dotShape:'round',invert:false},levels:{blackPoint:0,gamma:1,whitePoint:255,contrast:1},mask:{threshold:0,strength:1,fadeRange:0},knockout:{enabled:false,color:'#ffffff',tolerance:8}}
const presets={Soft:{dpi:300,halftone:{lpi:25,angle:45,dotShape:'round',invert:false},levels:{blackPoint:8,gamma:1.08,whitePoint:245,contrast:1.03}},Standard:{dpi:300,halftone:{lpi:30,angle:45,dotShape:'round',invert:false},levels:{blackPoint:4,gamma:1,whitePoint:250,contrast:1.05}},Fine:{dpi:300,halftone:{lpi:40,angle:45,dotShape:'round',invert:false},levels:{blackPoint:0,gamma:.95,whitePoint:255,contrast:1.08}},Vintage:{dpi:300,halftone:{lpi:22,angle:45,dotShape:'ellipse',invert:false},levels:{blackPoint:18,gamma:1.15,whitePoint:235,contrast:.92}}} as const
function mergeSettings(base:AppSettings,patch:Partial<AppSettings>):AppSettings{return {...base,...patch,halftone:{...base.halftone,...patch.halftone},levels:{...base.levels,...patch.levels},mask:{...base.mask,...patch.mask},knockout:{...base.knockout,...patch.knockout}}}
function download(blob:Blob,name:string){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function stageImage(p:ProcessedImage,mode:PreviewMode):ImageData{return mode==='mask'?p.mask:p[mode]}
function Stage({data,mode,garment}:{data:ImageData;mode:PreviewMode;garment:string}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{if(!ref.current)return;const c=ref.current;c.width=data.width;c.height=data.height;const ctx=c.getContext('2d')!;ctx.clearRect(0,0,c.width,c.height);if(mode==='mask'){ctx.fillStyle=garment;ctx.fillRect(0,0,c.width,c.height)}ctx.drawImage(imageDataToCanvas(data),0,0)},[data,mode,garment]);return <canvas ref={ref} className="stage-canvas"/>}
export default function App(){
 const [settings,setSettings]=useState<AppSettings>(defaults),[processed,setProcessed]=useState<ProcessedImage|null>(null),[fileName,setFileName]=useState(''),[mode,setMode]=useState<PreviewMode>('final'),[busy,setBusy]=useState(false),[zoom,setZoom]=useState(1),[garment,setGarment]=useState('#111111');const input=useRef<HTMLInputElement>(null)
 const apply=(fn:(s:AppSettings)=>AppSettings)=>setSettings(s=>fn(s));
 const load=useCallback(async(file:File)=>{if(!file.type.startsWith('image/'))return;setBusy(true);setFileName(file.name);try{const bmp=await createImageBitmap(file),max=5000,scale=Math.min(1,max/Math.max(bmp.width,bmp.height)),w=Math.max(1,Math.round(bmp.width*scale)),h=Math.max(1,Math.round(bmp.height*scale));const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d')!.drawImage(bmp,0,0,w,h);setProcessed(processImage(c.getContext('2d')!.getImageData(0,0,w,h),settings));setMode('final');setZoom(1);bmp.close()}finally{setBusy(false)}},[settings])
 useEffect(()=>{if(processed){setBusy(true);const id=requestAnimationFrame(()=>{setProcessed(processImage(processed.original,settings));setBusy(false)});return()=>cancelAnimationFrame(id)}},[settings])
 const current=processed?stageImage(processed,mode):null
 const setNum=(path:string,v:number)=>apply(s=>{const n={...s};const [a,b]=path.split('.');(n as any)[a][b]=v;return n})
 const auto=()=>{if(!processed)return;const d=processed.original.data;let sum=0,low=255,high=0;for(let i=0;i<d.length;i+=16){const l=.2126*d[i]+.7152*d[i+1]+.0722*d[i+2];sum+=l;low=Math.min(low,l);high=Math.max(high,l)}const avg=sum/(d.length/16);const contrast=Math.max(.92,Math.min(1.14,1+(avg<110?.06:avg>190?-.04:.02)));apply(s=>mergeSettings(s,{levels:{...s.levels,blackPoint:Math.round(low),whitePoint:Math.round(high),contrast}}))}
 const exportFinal=async()=>{if(processed){const b=await imageDataToBlob(processed.final);download(b,`${fileName.replace(/\.[^.]+$/,'')||'zank-halftone'}-DTF.png`)}}
 const exportMask=async()=>{if(processed){const b=await imageDataToBlob(processed.mask);download(b,`${fileName.replace(/\.[^.]+$/,'')||'zank-halftone'}-MASK.png`)}}
 const batch=async(files:FileList)=>{const zip=new JSZip();for(const f of Array.from(files)){const bmp=await createImageBitmap(f),max=5000,scale=Math.min(1,max/Math.max(bmp.width,bmp.height)),w=Math.round(bmp.width*scale),h=Math.round(bmp.height*scale),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d')!.drawImage(bmp,0,0,w,h);bmp.close();const p=processImage(c.getContext('2d')!.getImageData(0,0,w,h),settings);zip.file(`${f.name.replace(/\.[^.]+$/,'')}-DTF.png`,await imageDataToBlob(p.final))}download(await zip.generateAsync({type:'blob'}),'ZANK-HALFTONE-BATCH.zip')}
 return <div className="app"><header><div className="brand">ZANK <span>HALFTONE</span></div><div className="top-actions"><label className="batch"><input type="file" multiple accept="image/*" onChange={e=>e.target.files&&batch(e.target.files)}/><span>Batch ZIP</span></label><button onClick={()=>setSettings(defaults)} title="Reset"><RotateCcw size={16}/></button></div></header><main>
 <aside className="sidebar"><section><div className="section-title">SOURCE</div><button className="upload" onClick={()=>input.current?.click()}><Upload size={18}/><span>{fileName||'Upload artwork'}</span><small>PNG · JPG · WEBP</small></button><input ref={input} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>e.target.files?.[0]&&load(e.target.files[0])}/></section>
 <section><div className="section-title">AI ASSIST</div><button className="ai" onClick={auto} disabled={!processed}><Sparkles size={17}/><span>Auto optimize tones</span></button><p className="hint">Local image analysis. No upload, API or credits.</p></section>
 <section><div className="section-title">PRESET</div><div className="preset-grid">{Object.entries(presets).map(([name,p])=><button key={name} onClick={()=>setSettings(s=>mergeSettings(s,p))}>{name}</button>)}</div></section>
 <section><div className="section-title">HALFTONE SCREEN</div><div className="control"><label>LPI <b>{settings.halftone.lpi}</b></label><input type="range" min="10" max="80" value={settings.halftone.lpi} onChange={e=>setNum('halftone.lpi',+e.target.value)}/></div><div className="row"><label>Angle <input type="number" min="0" max="180" value={settings.halftone.angle} onChange={e=>setNum('halftone.angle',+e.target.value)}/></label><label>Shape <select value={settings.halftone.dotShape} onChange={e=>apply(s=>({...s,halftone:{...s.halftone,dotShape:e.target.value as DotShape}}))}><option value="round">Round</option><option value="ellipse">Ellipse</option><option value="square">Square</option><option value="line">Line</option></select></label></div><label className="check"><input type="checkbox" checked={settings.halftone.invert} onChange={e=>apply(s=>({...s,halftone:{...s.halftone,invert:e.target.checked}}))}/> Invert screen</label></section>
 <section><div className="section-title">LEVELS</div>{[['blackPoint','Black',0,255,1],['gamma','Gamma',.5,2,.01],['whitePoint','White',0,255,1],['contrast','Contrast',.5,1.5,.01]].map(([k,l,min,max,step])=><div className="control" key={String(k)}><label>{l} <b>{(settings.levels as any)[k]}</b></label><input type="range" min={String(min)} max={String(max)} step={String(step)} value={(settings.levels as any)[k]} onChange={e=>setNum(`levels.${k}`,+e.target.value)}/></div>)}</section>
 <section><div className="section-title">MASK</div><div className="control"><label>Threshold <b>{settings.mask.threshold}</b></label><input type="range" min="0" max="255" value={settings.mask.threshold} onChange={e=>setNum('mask.threshold',+e.target.value)}/></div><div className="control"><label>Fade <b>{settings.mask.fadeRange}</b></label><input type="range" min="0" max="255" value={settings.mask.fadeRange} onChange={e=>setNum('mask.fadeRange',+e.target.value)}/></div></section>
 <section><div className="section-title">DOCUMENT</div><div className="row"><label>DPI <select value={settings.dpi} onChange={e=>apply(s=>({...s,dpi:+e.target.value}))}><option value="300">300</option><option value="600">600</option></select></label><label>Garment <input type="color" value={garment} onChange={e=>setGarment(e.target.value)}/></label></div><label className="check"><input type="checkbox" checked={settings.knockout.enabled} onChange={e=>apply(s=>({...s,knockout:{...s.knockout,enabled:e.target.checked}}))}/> Color knockout</label>{settings.knockout.enabled&&<div className="row"><input type="color" value={settings.knockout.color} onChange={e=>apply(s=>({...s,knockout:{...s.knockout,color:e.target.value}}))}/><input type="range" min="0" max="80" value={settings.knockout.tolerance} onChange={e=>apply(s=>({...s,knockout:{...s, tolerance:+e.target.value}}))}/></div>}</section></aside>
 <section className="workspace"><div className="toolbar"><div><span className="status-dot"/> {busy?'PROCESSING':'READY'} {processed&&<em>{processed.width} × {processed.height}px</em>}</div><div className="views">{(['original','grayscale','levels','mask','final'] as PreviewMode[]).map(m=><button className={mode===m?'active':''} key={m} onClick={()=>setMode(m)}>{m==='original'?'Original':m==='grayscale'?'Gray':m==='levels'?'Levels':m==='mask'?'Mask':'Final'}</button>)}</div></div><div className="stage-wrap">{current?<div className="checker"><Stage data={current} mode={mode} garment={garment}/></div>:<div className="empty"><ImagePlus size={34}/><strong>Drop artwork here</strong><span>Build a production-ready DTF halftone locally in your browser.</span><button onClick={()=>input.current?.click()}>Choose image</button></div>}</div><div className="bottom"><div className="caption"><Eye size={15}/> {mode==='original'?'Original':mode==='grayscale'?'Grayscale':mode==='levels'?'Levels':mode==='mask'?'Halftone Mask':'Final DTF'}<span>•</span>{settings.halftone.lpi} LPI / {settings.halftone.angle}° / {settings.halftone.dotShape}</div><div className="zoom"><button onClick={()=>setZoom(z=>Math.max(.5,z-.1))}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(2,z+.1))}>+</button></div></div></section>
 <aside className="export"><div className="section-title">EXPORT</div><button className="export-main" disabled={!processed||busy} onClick={exportFinal}><Download size={18}/><span>Transparent PNG</span><small>Final DTF artwork</small></button><button className="export-secondary" disabled={!processed||busy} onClick={exportMask}>Export mask</button><div className="spec"><div><span>FORMAT</span><b>PNG</b></div><div><span>DPI</span><b>{settings.dpi}</b></div><div><span>ALPHA</span><b>ORIGINAL × MASK</b></div></div><div className="note"><Info size={14}/><span>All processing happens on this device. Your artwork is not sent to a server.</span></div></aside></main></div>
}
